//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.12 at 02:17:48 PM CEST 
//


package it.mygeo.project.service.robot.bean;

import org.simpleframework.xml.Element;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://bean.robot.service.project.mygeo.it}southwest"/>
 *         &lt;element ref="{http://bean.robot.service.project.mygeo.it}northeast"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */

public class Bounds {

    @Element(required = false)
    protected Southwest southwest;
    @Element(required = false)
    protected Northeast northeast;

    /**
     * Gets the value of the southwest property.
     * 
     * @return
     *     possible object is
     *     {@link Southwest }
     *     
     */
    public Southwest getSouthwest() {
        return southwest;
    }

    /**
     * Sets the value of the southwest property.
     * 
     * @param value
     *     allowed object is
     *     {@link Southwest }
     *     
     */
    public void setSouthwest(Southwest value) {
        this.southwest = value;
    }

    /**
     * Gets the value of the northeast property.
     * 
     * @return
     *     possible object is
     *     {@link Northeast }
     *     
     */
    public Northeast getNortheast() {
        return northeast;
    }

    /**
     * Sets the value of the northeast property.
     * 
     * @param value
     *     allowed object is
     *     {@link Northeast }
     *     
     */
    public void setNortheast(Northeast value) {
        this.northeast = value;
    }

}
