//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.12 at 02:17:48 PM CEST 
//


package it.mygeo.project.service.robot.bean;

import org.simpleframework.xml.Element;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://bean.robot.service.project.mygeo.it}step"/>
 *         &lt;element ref="{http://bean.robot.service.project.mygeo.it}duration"/>
 *         &lt;element ref="{http://bean.robot.service.project.mygeo.it}distance"/>
 *         &lt;element ref="{http://bean.robot.service.project.mygeo.it}start_location"/>
 *         &lt;element ref="{http://bean.robot.service.project.mygeo.it}end_location"/>
 *         &lt;element ref="{http://bean.robot.service.project.mygeo.it}start_address"/>
 *         &lt;element ref="{http://bean.robot.service.project.mygeo.it}end_address"/>
 *         &lt;element ref="{http://bean.robot.service.project.mygeo.it}departure_time"/>
 *         &lt;element ref="{http://bean.robot.service.project.mygeo.it}arrival_time"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */

public class Leg {

    @Element(required = false)
    protected Step step;
    @Element(required = false)
    protected Duration duration;
    @Element(required = false)
    protected Distance distance;
    @Element(name = "start_location", required = false)
    protected StartLocation startLocation;
    @Element(name = "end_location", required = false)
    protected EndLocation endLocation;
    @Element(name = "start_address", required = false)
    protected String startAddress;
    @Element(name = "end_address", required = false)
    protected String endAddress;
    @Element(name = "departure_time", required = false)
    protected DepartureTime departureTime;
    @Element(name = "arrival_time", required = false)
    protected ArrivalTime arrivalTime;

    /**
     * Gets the value of the step property.
     * 
     * @return
     *     possible object is
     *     {@link Step }
     *     
     */
    public Step getStep() {
        return step;
    }

    /**
     * Sets the value of the step property.
     * 
     * @param value
     *     allowed object is
     *     {@link Step }
     *     
     */
    public void setStep(Step value) {
        this.step = value;
    }

    /**
     * Gets the value of the duration property.
     * 
     * @return
     *     possible object is
     *     {@link Duration }
     *     
     */
    public Duration getDuration() {
        return duration;
    }

    /**
     * Sets the value of the duration property.
     * 
     * @param value
     *     allowed object is
     *     {@link Duration }
     *     
     */
    public void setDuration(Duration value) {
        this.duration = value;
    }

    /**
     * Gets the value of the distance property.
     * 
     * @return
     *     possible object is
     *     {@link Distance }
     *     
     */
    public Distance getDistance() {
        return distance;
    }

    /**
     * Sets the value of the distance property.
     * 
     * @param value
     *     allowed object is
     *     {@link Distance }
     *     
     */
    public void setDistance(Distance value) {
        this.distance = value;
    }

    /**
     * Gets the value of the startLocation property.
     * 
     * @return
     *     possible object is
     *     {@link StartLocation }
     *     
     */
    public StartLocation getStartLocation() {
        return startLocation;
    }

    /**
     * Sets the value of the startLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link StartLocation }
     *     
     */
    public void setStartLocation(StartLocation value) {
        this.startLocation = value;
    }

    /**
     * Gets the value of the endLocation property.
     * 
     * @return
     *     possible object is
     *     {@link EndLocation }
     *     
     */
    public EndLocation getEndLocation() {
        return endLocation;
    }

    /**
     * Sets the value of the endLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link EndLocation }
     *     
     */
    public void setEndLocation(EndLocation value) {
        this.endLocation = value;
    }

    /**
     * Gets the value of the startAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStartAddress() {
        return startAddress;
    }

    /**
     * Sets the value of the startAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStartAddress(String value) {
        this.startAddress = value;
    }

    /**
     * Gets the value of the endAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEndAddress() {
        return endAddress;
    }

    /**
     * Sets the value of the endAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEndAddress(String value) {
        this.endAddress = value;
    }

    /**
     * Gets the value of the departureTime property.
     * 
     * @return
     *     possible object is
     *     {@link DepartureTime }
     *     
     */
    public DepartureTime getDepartureTime() {
        return departureTime;
    }

    /**
     * Sets the value of the departureTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link DepartureTime }
     *     
     */
    public void setDepartureTime(DepartureTime value) {
        this.departureTime = value;
    }

    /**
     * Gets the value of the arrivalTime property.
     * 
     * @return
     *     possible object is
     *     {@link ArrivalTime }
     *     
     */
    public ArrivalTime getArrivalTime() {
        return arrivalTime;
    }

    /**
     * Sets the value of the arrivalTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrivalTime }
     *     
     */
    public void setArrivalTime(ArrivalTime value) {
        this.arrivalTime = value;
    }

}
