//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.12 at 02:17:48 PM CEST 
//


package it.mygeo.project.service.robot.bean;

import org.simpleframework.xml.Element;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://bean.robot.service.project.mygeo.it}short_name"/>
 *         &lt;element ref="{http://bean.robot.service.project.mygeo.it}vehicle"/>
 *         &lt;element ref="{http://bean.robot.service.project.mygeo.it}agency"/>
 *         &lt;element ref="{http://bean.robot.service.project.mygeo.it}color"/>
 *         &lt;element ref="{http://bean.robot.service.project.mygeo.it}text_color"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */

public class Line {

    @Element(name = "url", required = false)
    protected String Url;
    @Element(name = "name", required = false)
    protected String Name;
    @Element(name = "short_name", required = false)
    protected String shortName;
    @Element(required = false)
    protected Vehicle vehicle;
    @Element(required = false)
    protected Agency agency;
    @Element(required = false)
    protected String color;
    @Element(name = "text_color", required = false)
    protected String textColor;

    /**
     * Gets the value of the shortName property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getShortName() {
        return shortName;
    }

    /**
     * Sets the value of the shortName property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setShortName(String value) {
        this.shortName = value;
    }

    /**
     * Gets the value of the vehicle property.
     *
     * @return
     *     possible object is
     *     {@link Vehicle }
     *
     */
    public Vehicle getVehicle() {
        return vehicle;
    }

    /**
     * Sets the value of the vehicle property.
     *
     * @param value
     *     allowed object is
     *     {@link Vehicle }
     *
     */
    public void setVehicle(Vehicle value) {
        this.vehicle = value;
    }

    /**
     * Gets the value of the agency property.
     *
     * @return
     *     possible object is
     *     {@link Agency }
     *
     */
    public Agency getAgency() {
        return agency;
    }

    /**
     * Sets the value of the agency property.
     *
     * @param value
     *     allowed object is
     *     {@link Agency }
     *
     */
    public void setAgency(Agency value) {
        this.agency = value;
    }

    /**
     * Gets the value of the color property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getColor() {
        return color;
    }

    /**
     * Sets the value of the color property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setColor(String value) {
        this.color = value;
    }

    /**
     * Gets the value of the textColor property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getTextColor() {
        return textColor;
    }

    /**
     * Sets the value of the textColor property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setTextColor(String value) {
        this.textColor = value;
    }

    public String getName() {
        return Name;
    }

    public void setName(String name) {
        Name = name;
    }

    public String getUrl() {
        return Url;
    }

    public void setUrl(String url) {
        Url = url;
    }



}
