//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.12 at 02:17:48 PM CEST 
//


package it.mygeo.project.service.robot.bean;

import org.simpleframework.xml.Element;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://bean.robot.service.project.mygeo.it}summary"/>
 *         &lt;element ref="{http://bean.robot.service.project.mygeo.it}leg"/>
 *         &lt;element ref="{http://bean.robot.service.project.mygeo.it}copyrights"/>
 *         &lt;element ref="{http://bean.robot.service.project.mygeo.it}overview_polyline"/>
 *         &lt;element ref="{http://bean.robot.service.project.mygeo.it}bounds"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */

public class Route {

   @Element(required=false)
    protected String summary;
   @Element(required=false)
    protected Leg leg;
   @Element(required=false)
    protected String copyrights;
    @Element(name = "overview_polyline", required = false)
    protected OverviewPolyline overviewPolyline;
   @Element(required=false)
    protected Bounds bounds;
   @Element(required=false)
   protected String warning;

    /**
     * Gets the value of the summary property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSummary() {
        return summary;
    }

    /**
     * Sets the value of the summary property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSummary(String value) {
        this.summary = value;
    }

    /**
     * Gets the value of the leg property.
     * 
     * @return
     *     possible object is
     *     {@link Leg }
     *     
     */
    public Leg getLeg() {
        return leg;
    }

    /**
     * Sets the value of the leg property.
     * 
     * @param value
     *     allowed object is
     *     {@link Leg }
     *     
     */
    public void setLeg(Leg value) {
        this.leg = value;
    }

    /**
     * Gets the value of the copyrights property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCopyrights() {
        return copyrights;
    }

    /**
     * Sets the value of the copyrights property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCopyrights(String value) {
        this.copyrights = value;
    }

    /**
     * Gets the value of the overviewPolyline property.
     * 
     * @return
     *     possible object is
     *     {@link OverviewPolyline }
     *     
     */
    public OverviewPolyline getOverviewPolyline() {
        return overviewPolyline;
    }

    /**
     * Sets the value of the overviewPolyline property.
     * 
     * @param value
     *     allowed object is
     *     {@link OverviewPolyline }
     *     
     */
    public void setOverviewPolyline(OverviewPolyline value) {
        this.overviewPolyline = value;
    }

    /**
     * Gets the value of the bounds property.
     * 
     * @return
     *     possible object is
     *     {@link Bounds }
     *     
     */
    public Bounds getBounds() {
        return bounds;
    }

    /**
     * Sets the value of the bounds property.
     * 
     * @param value
     *     allowed object is
     *     {@link Bounds }
     *     
     */
    public void setBounds(Bounds value) {
        this.bounds = value;
    }

	public String getWarning() {
		return warning;
	}

	public void setWarning(String warning) {
		this.warning = warning;
	}
    
    

}
