//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.12 at 02:17:48 PM CEST 
//


package it.mygeo.project.service.robot.bean;

import java.util.ArrayList;
import java.util.List;

import org.simpleframework.xml.Element;
import org.simpleframework.xml.ElementList;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://bean.robot.service.project.mygeo.it}travel_mode"/>
 *         &lt;element ref="{http://bean.robot.service.project.mygeo.it}start_location"/>
 *         &lt;element ref="{http://bean.robot.service.project.mygeo.it}end_location"/>
 *         &lt;element ref="{http://bean.robot.service.project.mygeo.it}polyline"/>
 *         &lt;element ref="{http://bean.robot.service.project.mygeo.it}duration"/>
 *         &lt;element ref="{http://bean.robot.service.project.mygeo.it}html_instructions"/>
 *         &lt;element ref="{http://bean.robot.service.project.mygeo.it}distance"/>
 *         &lt;element ref="{http://bean.robot.service.project.mygeo.it}transit_details"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */

public class Step {

    @Element(name = "travel_mode", required = false)
    protected String travelMode;
    @Element(name = "start_location", required = false)
    protected StartLocation startLocation;
    @Element(name = "end_location", required = false)
    protected EndLocation endLocation;
    @Element(required = false)
    protected Polyline polyline;
    @Element(required = false)
    protected Duration duration;
    @Element(name = "html_instructions", required = false)
    protected String htmlInstructions;
    @Element(required = false)
    protected Distance distance;
    @Element(name = "transit_details", required = false)
    protected TransitDetails transitDetails;
    @ElementList(entry="step", inline=true, required = false)
    protected List<Step> step;

    /**
     * Gets the value of the travelMode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTravelMode() {
        return travelMode;
    }

    /**
     * Sets the value of the travelMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTravelMode(String value) {
        this.travelMode = value;
    }

    /**
     * Gets the value of the startLocation property.
     * 
     * @return
     *     possible object is
     *     {@link StartLocation }
     *     
     */
    public StartLocation getStartLocation() {
        return startLocation;
    }

    /**
     * Sets the value of the startLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link StartLocation }
     *     
     */
    public void setStartLocation(StartLocation value) {
        this.startLocation = value;
    }

    /**
     * Gets the value of the endLocation property.
     * 
     * @return
     *     possible object is
     *     {@link EndLocation }
     *     
     */
    public EndLocation getEndLocation() {
        return endLocation;
    }

    /**
     * Sets the value of the endLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link EndLocation }
     *     
     */
    public void setEndLocation(EndLocation value) {
        this.endLocation = value;
    }

    /**
     * Gets the value of the polyline property.
     * 
     * @return
     *     possible object is
     *     {@link Polyline }
     *     
     */
    public Polyline getPolyline() {
        return polyline;
    }

    /**
     * Sets the value of the polyline property.
     * 
     * @param value
     *     allowed object is
     *     {@link Polyline }
     *     
     */
    public void setPolyline(Polyline value) {
        this.polyline = value;
    }

    /**
     * Gets the value of the duration property.
     * 
     * @return
     *     possible object is
     *     {@link Duration }
     *     
     */
    public Duration getDuration() {
        return duration;
    }

    /**
     * Sets the value of the duration property.
     * 
     * @param value
     *     allowed object is
     *     {@link Duration }
     *     
     */
    public void setDuration(Duration value) {
        this.duration = value;
    }

    /**
     * Gets the value of the htmlInstructions property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHtmlInstructions() {
        return htmlInstructions;
    }

    /**
     * Sets the value of the htmlInstructions property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHtmlInstructions(String value) {
        this.htmlInstructions = value;
    }

    /**
     * Gets the value of the distance property.
     * 
     * @return
     *     possible object is
     *     {@link Distance }
     *     
     */
    public Distance getDistance() {
        return distance;
    }

    /**
     * Sets the value of the distance property.
     * 
     * @param value
     *     allowed object is
     *     {@link Distance }
     *     
     */
    public void setDistance(Distance value) {
        this.distance = value;
    }

    /**
     * Gets the value of the transitDetails property.
     * 
     * @return
     *     possible object is
     *     {@link TransitDetails }
     *     
     */
    public TransitDetails getTransitDetails() {
        return transitDetails;
    }

    /**
     * Sets the value of the transitDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransitDetails }
     *     
     */
    public void setTransitDetails(TransitDetails value) {
        this.transitDetails = value;
    }
    
    public List<Step> getStep() {
        if (step == null) {
        	step = new ArrayList<Step>();
        }
        return this.step;
    }

}
