//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.12 at 02:17:48 PM CEST 
//


package it.mygeo.project.service.robot.bean;

import org.simpleframework.xml.Element;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://bean.robot.service.project.mygeo.it}departure_stop"/>
 *         &lt;element ref="{http://bean.robot.service.project.mygeo.it}arrival_stop"/>
 *         &lt;element ref="{http://bean.robot.service.project.mygeo.it}line"/>
 *         &lt;element ref="{http://bean.robot.service.project.mygeo.it}num_stops"/>
 *         &lt;element ref="{http://bean.robot.service.project.mygeo.it}headsign"/>
 *         &lt;element ref="{http://bean.robot.service.project.mygeo.it}departure_time"/>
 *         &lt;element ref="{http://bean.robot.service.project.mygeo.it}arrival_time"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */

public class TransitDetails {

    @Element(name = "departure_stop", required = false)
    protected DepartureStop departureStop;
    @Element(name = "arrival_stop", required = false)
    protected ArrivalStop arrivalStop;
    @Element(required = false)
    protected Line line;
    @Element(name = "num_stops", required = false)
    protected String numStops;
    @Element(required = false)
    protected String headsign;
    @Element(name = "departure_time", required = false)
    protected DepartureTime departureTime;
    @Element(name = "arrival_time", required = false)
    protected ArrivalTime arrivalTime;

    /**
     * Gets the value of the departureStop property.
     * 
     * @return
     *     possible object is
     *     {@link DepartureStop }
     *     
     */
    public DepartureStop getDepartureStop() {
        return departureStop;
    }

    /**
     * Sets the value of the departureStop property.
     * 
     * @param value
     *     allowed object is
     *     {@link DepartureStop }
     *     
     */
    public void setDepartureStop(DepartureStop value) {
        this.departureStop = value;
    }

    /**
     * Gets the value of the arrivalStop property.
     * 
     * @return
     *     possible object is
     *     {@link ArrivalStop }
     *     
     */
    public ArrivalStop getArrivalStop() {
        return arrivalStop;
    }

    /**
     * Sets the value of the arrivalStop property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrivalStop }
     *     
     */
    public void setArrivalStop(ArrivalStop value) {
        this.arrivalStop = value;
    }

    /**
     * Gets the value of the line property.
     * 
     * @return
     *     possible object is
     *     {@link Line }
     *     
     */
    public Line getLine() {
        return line;
    }

    /**
     * Sets the value of the line property.
     * 
     * @param value
     *     allowed object is
     *     {@link Line }
     *     
     */
    public void setLine(Line value) {
        this.line = value;
    }

    /**
     * Gets the value of the numStops property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumStops() {
        return numStops;
    }

    /**
     * Sets the value of the numStops property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumStops(String value) {
        this.numStops = value;
    }

    /**
     * Gets the value of the headsign property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHeadsign() {
        return headsign;
    }

    /**
     * Sets the value of the headsign property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHeadsign(String value) {
        this.headsign = value;
    }

    /**
     * Gets the value of the departureTime property.
     * 
     * @return
     *     possible object is
     *     {@link DepartureTime }
     *     
     */
    public DepartureTime getDepartureTime() {
        return departureTime;
    }

    /**
     * Sets the value of the departureTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link DepartureTime }
     *     
     */
    public void setDepartureTime(DepartureTime value) {
        this.departureTime = value;
    }

    /**
     * Gets the value of the arrivalTime property.
     * 
     * @return
     *     possible object is
     *     {@link ArrivalTime }
     *     
     */
    public ArrivalTime getArrivalTime() {
        return arrivalTime;
    }

    /**
     * Sets the value of the arrivalTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrivalTime }
     *     
     */
    public void setArrivalTime(ArrivalTime value) {
        this.arrivalTime = value;
    }

}
